const {chromium}=require('/Users/ethanstudio/.agents/skills/fb-post/node_modules/playwright');const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),base='http://127.0.0.1:8940/';const data=JSON.parse(fs.readFileSync(__dirname+'/video-sources.json'));const rows=data.records,core=rows.filter(r=>r.learning_tier==='core');const errors=[];p.on('pageerror',e=>errors.push(e.message));const results=[];fs.mkdirSync(__dirname+'/docs/sources-screens',{recursive:true});
await p.goto(base+'dist/');assert.equal(await p.title(),'運動醫學影像學習站');assert.equal(await p.locator('h1').textContent(),'運動醫學影像學習站');assert.equal(await p.locator('.route-panel').evaluate(e=>getComputedStyle(e).borderTopWidth),'0px');assert.equal(await p.locator('.source-site-list li').count(),7);
await p.locator('.source-site-list a[href*="site=hip"]').click();await p.locator('.source-controls').waitFor();assert.equal(await p.locator('#source-site').inputValue(),'hip');assert.equal(await p.locator('.video-record:visible').count(),25);
await p.locator('#source-reset').click();assert.equal(await p.locator('.video-record:visible').count(),core.length);assert.equal(await p.locator('.provider-record').count(),39);assert.equal(await p.locator('.provider-importance').count(),39);assert.equal(await p.locator('.provider-background').count(),39);
for(const s of JSON.parse(fs.readFileSync(__dirname+'/courses.json'))){await p.locator('#source-site').selectOption(s.id);assert.equal(await p.locator('.video-record:visible').count(),core.filter(r=>r.site===s.id).length);results.push(s.id+' core mapping');}
await p.locator('#source-reset').click();await p.locator('#source-tier').selectOption('all');assert.equal(await p.locator('.video-record:visible').count(),rows.length);
await p.locator('#source-search').fill('no-matching-source-xyz');assert.equal(await p.locator('.video-record:visible').count(),0);assert.ok(await p.locator('#source-empty').isVisible());await p.locator('#source-reset').click();
await p.locator('#source-search').fill('AMSSM');assert.ok(await p.locator('.video-record:visible').count()>=8);await p.locator('#source-reset').click();
const provider=p.locator('.provider-record').filter({has:p.locator('[data-source-channel="The AMSSM"]')});await provider.locator('summary').click();await provider.locator('[data-source-channel]').click();assert.equal(await p.locator('.video-record:visible').count(),8);assert.equal(await p.evaluate(()=>document.activeElement.id),'videos-title');
await p.locator('#source-reset').click();const first=p.locator('.video-record:visible').first();await first.locator('summary').focus();await p.keyboard.press('Enter');assert.equal(await first.getAttribute('open'),'');assert.match(await first.locator('.video-detail').textContent(),/教學重要性/);
for(const width of [320,390,768,1440])for(const theme of ['light','dark']){await p.setViewportSize({width,height:1000});await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await first.evaluate(e=>e.scrollWidth<=e.clientWidth+1));results.push(`${width} ${theme}`);if(width===390)await p.screenshot({path:__dirname+`/docs/sources-screens/${theme}-390.png`});}
await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>document.documentElement.dataset.theme='light');await p.goto(base+'preview/sources.html?site=knee#videos');await p.locator('.source-controls').waitFor();await p.locator('.video-record:visible').first().locator('summary').click();const unitLinks=await p.locator('.video-record[data-site="knee"] .source-actions a:first-child').evaluateAll(es=>es.map(e=>e.href));assert.equal(unitLinks.length,rows.filter(r=>r.site==='knee').length);assert.ok(unitLinks.every(u=>u.startsWith('http://127.0.0.1:8937/')));await p.screenshot({path:__dirname+'/docs/sources-screens/core-list.png'});
const nojs=await b.newContext({javaScriptEnabled:false});const n=await nojs.newPage();await n.goto(base+'dist/sources.html');assert.equal(await n.locator('.video-record').count(),rows.length);await n.locator('.video-record').first().locator('summary').click();assert.ok(await n.locator('.video-detail').first().isVisible());
assert.equal(await n.locator('a[download], a[href$=".csv"]').count(),0);
assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/docs/sources-validation.json',JSON.stringify({placements:rows.length,core:core.length,uniqueCore:new Set(core.map(r=>r.video_id)).size,coreChannels:39,results,checks:['title','no decorative border','7 site links','core/all filters','channel link and keyboard focus','search and reset','per-video importance','no CSV download links','preview URLs','no-JS full list'],errors},null,2));await nojs.close();await b.close();console.log('PASS video sources, coverage, responsive and controls');})().catch(e=>{console.error(e);process.exit(1)});
